export const StateList = ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir ', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana ', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']
export const SeasonList = ['Kharif     ',
    'Whole Year ',
    'Autumn     ',
    'Rabi       ',
    'Summer     ',
    'Winter     '];

export const CropList = ['Arecanut',
    'Other Kharif pulses',
    'Rice',
    'Banana',
    'Cashewnut',
    'Coconut ',
    'Dry ginger',
    'Sugarcane',
    'Sweet potato',
    'Tapioca',
    'Black pepper',
    'Dry chillies',
    'other oilseeds',
    'Turmeric',
    'Maize',
    'Moong(Green Gram)',
    'Urad',
    'Arhar/Tur',
    'Groundnut',
    'Sunflower',
    'Bajra',
    'Castor seed',
    'Cotton(lint)',
    'Horse-gram',
    'Jowar',
    'Korra',
    'Ragi',
    'Tobacco',
    'Gram',
    'Wheat',
    'Masoor',
    'Sesamum',
    'Linseed',
    'Safflower',
    'Onion',
    'other misc. pulses',
    'Samai',
    'Small millets',
    'Coriander',
    'Potato',
    'Other  Rabi pulses',
    'Soyabean',
    'Beans & Mutter(Vegetable)',
    'Bhindi',
    'Brinjal',
    'Citrus Fruit',
    'Cucumber',
    'Grapes',
    'Mango',
    'Orange',
    'other fibres',
    'Other Fresh Fruits',
    'Other Vegetables',
    'Papaya',
    'Pome Fruit',
    'Tomato',
    'Rapeseed &Mustard',
    'Mesta',
    'Cowpea(Lobia)',
    'Lemon',
    'Pome Granet',
    'Sapota',
    'Cabbage',
    'Peas  (vegetable)',
    'Niger seed',
    'Bottle Gourd',
    'Sannhamp',
    'Varagu',
    'Garlic',
    'Ginger',
    'Oilseeds total',
    'Pulses total',
    'Jute',
    'Peas & beans (Pulses)',
    'Blackgram',
    'Paddy',
    'Pineapple',
    'Barley',
    'Khesari',
    'Guar seed',
    'Moth',
    'Other Cereals & Millets',
    'Cond-spcs other',
    'Turnip',
    'Carrot',
    'Redish',
    'Arcanut (Processed)',
    'Atcanut (Raw)',
    'Cashewnut Processed',
    'Cashewnut Raw',
    'Cardamom',
    'Rubber',
    'Bitter Gourd',
    'Drum Stick',
    'Jack Fruit',
    'Snak Guard',
    'Pump Kin',
    'Tea',
    'Coffee',
    'Cauliflower',
    'Other Citrus Fruit',
    'Water Melon',
    'Total foodgrain',
    'Kapas',
    'Colocosia',
    'Lentil',
    'Bean',
    'Jobster',
    'Perilla',
    'Rajmash Kholar',
    'Ricebean (nagadal)',
    'Ash Gourd',
    'Beet Root',
    'Lab-Lab',
    'Ribed Guard',
    'Yam',
    'Apple',
    'Peach',
    'Pear',
    'Plums',
    'Litchi',
    'Ber',
    'Other Dry Fruit',
    'Jute & mesta']

export const ImageLinks = {
    'Arecanut': 'https://5.imimg.com/data5/SELLER/Default/2021/4/AI/XU/QE/8387819/arecanut-1000x1000.png',
    'Other Kharif pulses': 'https://live.staticflickr.com/8721/28466326395_d33b68ca85_z.jpg',
    'rice': 'https://tse3.mm.bing.net/th?id=OIP._wQfHMqK00-Botm4s8z0vwHaFj&pid=Api&P=0',
    'Banana': 'https://tse4.mm.bing.net/th?id=OIP.hBd5NqxuSoDhAI1k5E7WKwHaE8&pid=Api&P=0',
    'Cashewnut': 'https://tse4.mm.bing.net/th?id=OIP.l7hoZ6DbiY6jdnb5PPH7DwHaHa&pid=Api&P=0',
    'cocunut': 'https://tse2.mm.bing.net/th?id=OIP.-NYj78iOSNzZx43RanjepQHaF0&pid=Api&P=0',
    'dry ginger': 'https://tse4.explicit.bing.net/th?id=OIP.RNfjqJX-A_u-YT8Y2DczegHaE8&pid=Api&P=0',
    'Sugarcane': 'https://tse3.mm.bing.net/th?id=OIP.F5rYwIUjhPd0Q2N8pXu6UwHaEo&pid=Api&P=0',
    'Sweet potato': 'https://tse3.mm.bing.net/th?id=OIP.did2gbG0SYKlHHFhBNLUoQHaFj&pid=Api&P=0',
    'Tapioca': 'https://i1.wp.com/phildigest.jp/wp-content/uploads/2019/11/SAGO_iStock-177866476.jpg',
    'Black pepper': 'https://5.imimg.com/data5/SELLER/Default/2021/2/WI/TR/GM/123440641/black-pepper.jpg',
    'Dry chillies': 'https://i.pinimg.com/originals/b6/16/67/b616670f49181d945bd824b0c4d943f6.jpg',
    'other oilseeds': 'https://tse1.mm.bing.net/th?id=OIP.R8Gp8ByyhSudHr9mcgER5gAAAA&pid=Api&P=0',
    'Turmeric': 'https://learningherbs.com/wp-content/uploads/2017/03/turmeric-1-1030x687.jpg',
    'Maize': 'https://tse4.mm.bing.net/th?id=OIP.Txbn7Q0xCQ61WduQ9cTY4gHaHF&pid=Api&P=0',
    'Moong(Green Gram)': 'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_episode/1203803/1203803-1559840990066-3c737742f5ef2.jpg',
    'Urad': 'https://www.harishfoodzone.com/jb-content/uploads/2020/06/Black-Urad-Dal-1img.jpg',
    'Arhar/Tur': 'https://tse2.mm.bing.net/th?id=OIP.LYZnbRM3xtf9f2-8KiSR8QHaHa&pid=Api&P=0',
    'Groundnut': 'https://tse1.mm.bing.net/th?id=OIP.CvE02-wEhs8b4ESDEVMs1AHaFj&pid=Api&P=0',
    'Sunflower': 'https://tse3.mm.bing.net/th?id=OIP.8M0CEjZIHbOOPBZZtbvPBgHaE7&pid=Api&P=0',
    'Bajra': 'https://www.crosfield.co/wp-content/uploads/2020/02/Benefits-Of-Bajra-Millet.jpg',
    'Castor seed': 'http://static.businessinsider.com/image/516ec3ad6bb3f73c2f000002/image.jpg',
    'Cotton(lint)': 'https://www.thehindubusinessline.com/opinion/editorial/vzolq1/article27957278.ece/ALTERNATES/LANDSCAPE_615/BL17THINKEDIT2',
    'Horse-gram': 'https://tse3.mm.bing.net/th?id=OIP.lgYn0AAk81rqVtSToH5E4gHaHa&pid=Api&P=0',
    'Jowar': 'https://www.hopscotch.in/blog/wp-content/uploads/2020/01/Jowar.jpg',
    'Ragi': 'https://images.newindianexpress.com/uploads/user/ckeditor_images/article/2021/5/4/ragi.jpg',
    'Tobacco': 'https://tse3.mm.bing.net/th?id=OIP.OivM4RKyQyYSob_GaEAHtQHaEz&pid=Api&P=0',
    'Gram': 'https://nammafarm.com/wp-content/uploads/2020/11/34-GREEN-GRAM-WHOLE-scaled.jpg',
    ' Wheat': 'https://tse1.mm.bing.net/th?id=OIP.kbr-QB-x8J6TE74JymSwxQHaLH&pid=Api&P=0',
    'Masoor': 'https://cdn.shopify.com/s/files/1/0251/6942/8589/products/image_2de68545-5b93-4ec9-9328-b5018ab5a686_1200x1200.jpg?v=1596652186',
    'Sesamum': 'https://tse2.mm.bing.net/th?id=OIP.nBX2VgBBhE6OQ0cnLOPLjgHaE8&pid=Api&P=0',
    'Linseed': 'https://tse1.mm.bing.net/th?id=OIP.kgpYAkZEnVR4klY2nEDyQAHaFI&pid=Api&P=0',
    'Safflower': 'https://tse3.mm.bing.net/th?id=OIP.6Y_m97LLtb9izJpkuk-89gHaE7&pid=Api&P=0',
    'Onion': 'https://tse2.mm.bing.net/th?id=OIP.CTzPCyt9hXj1tBhrrCXqMwHaFO&pid=Api&P=0',
    'Small millets': 'https://thumbs.dreamstime.com/b/small-millet-grains-croup-wooden-bowl-spoon-113630547.jpg',
    'Coriander': 'https://tse2.mm.bing.net/th?id=OIP.pnm1KnFRGBJ58jk2-6abkwHaF0&pid=Api&P=0',
    'Potato': 'https://img.crocdn.co.uk/images/products2/pl/20/00/02/34/pl2000023450.jpg?width=940&height=940',
    'Other  Rabi pulses': 'https://static.toiimg.com/thumb/msid-52745372,imgsize-90248,width-400,resizemode-4/52745372.jpg',
    'Soyabean': 'https://nepc.gov.ng/cms/wp-content/uploads/2020/10/nepc-soya-beans-1024x683.jpg',
    'Beans & Mutter(Vegetable)': 'https://cdn.shopclues.com/images/detailed/19905/Matarseed_1434511694.jpg',
    'Bhindi': 'https://tse4.mm.bing.net/th?id=OIP._whACDc72sE921mVySmZ9QHaE7&pid=Api&P=0',
    'Brinjal': 'https://2.bp.blogspot.com/-G-xJKXBcaBk/TiUUuD6jV_I/AAAAAAAABgg/TtMXH0j_XFw/s1600/DSCN1072.JPG',
    'Citrus Fruit': 'https://tse3.mm.bing.net/th?id=OIP.luAIP7ugsr3RbWM1d57KxwHaFv&pid=Api&P=0',
    'Cucumber': 'https://tse1.mm.bing.net/th?id=OIP.nwG3B11JRphtI1EgrBeLSwHaHa&pid=Api&P=0',
    'Grapes': 'https://tse1.mm.bing.net/th?id=OIP.1bplT06DbNyGgawVrmfpoQHaLH&pid=Api&P=0',
    'Mango': 'https://www.thespruce.com/thmb/p40FNwOEgo0gEU8yYH6t2Hacsg8=/2318x0/filters:no_upscale():max_bytes(150000):strip_icc()/grow-mango-seeds-1902625-05-73d31c720a0947cea796163d4d113869.jpg',
    'Orange': 'https://tse1.mm.bing.net/th?id=OIP.2Y4M3RxTbEOzDYr-LBWouAHaFj&pid=Api&P=0',
    'Other Fresh Fruits': 'https://goqii.com/blog/wp-content/uploads/shutterstock_519340927.jpg',
    'Other Vegetables': 'https://tse4.mm.bing.net/th?id=OIP.Rnx5LmMIe_CTrMw7vwtkKAHaEo&pid=Api&P=0',
    'Papaya': 'https://www.gardeningknowhow.com/wp-content/uploads/2020/05/papaya.jpg',
    'Pome Fruit': 'https://tse3.mm.bing.net/th?id=OIP._XGdGjuV78GtgtQAjYeRywHaE7&pid=Api&P=0',
    'Tomato': 'https://www.gardeningknowhow.com/wp-content/uploads/2019/07/tomatoes.jpg',
    'Rapeseed &Mustard': 'https://tse2.mm.bing.net/th?id=OIP.wT8dIEh4G6ZkVHKOSlyamAHaE9&pid=Api&P=0',
    'Cowpea(Lobia)': 'https://tse1.mm.bing.net/th?id=OIP.Zfu0dg1lP2mJ4mUiEfXibAHaHa&pid=Api&P=0',
    'Lemon': 'https://tse4.mm.bing.net/th?id=OIP.rFrodg7e9cBd90QxT26d7QHaGc&pid=Api&P=0',
    'Pome Granet': 'https://www.thespruce.com/thmb/Dx4WmB6YLkYYadhZQ90SeAeahiE=/2126x1412/filters:fill(auto,1)/155351657-56a98c8c3df78cf772a82cd7.jpg',
    'Sapota': 'https://tse2.mm.bing.net/th?id=OIP.SMa6ndY_S7_QkK-OJb_KbQHaE9&pid=Api&P=0',
    'Cabbage': 'https://northernnester.com/wp-content/uploads/2020/02/how-to-store-cabbage.jpg',
    'Peas  (vegetable)': 'https://tse4.mm.bing.net/th?id=OIP.GJiWi30ey_qK5FU-x7Ac3gHaFj&pid=Api&P=0',
    'Niger seed': 'https://www.gunatitimpex.com/wp-content/uploads/2019/09/Niger-Seeds-1.jpg',
    'Bottle Gourd': 'https://tse1.mm.bing.net/th?id=OIP._lh_zukx2sYJLCxKRGmKKgHaHb&pid=Api&P=0',
    'Varagu': 'https://www.harishfoodzone.com/jb-content/uploads/2020/06/Varagu-Rice-1img-768x768.jpg',
    'Garlic': 'https://tse2.mm.bing.net/th?id=OIP.3BfeSPhvBax3W2ONd6TRJQHaE7&pid=Api&P=0',
    'Ginger': 'https://tse4.mm.bing.net/th?id=OIP.L0m5WmNGgzrFAIY3O2o2kwHaFV&pid=Api&P=0',
    'Oilseeds total': 'https://img3.exportersindia.com/product_images/bc-full/dir_60/1792797/oil-seed-506981.jpg',
    'Pulses total': 'https://tse4.mm.bing.net/th?id=OIP.By_rmA2GCYuOX5BBOC39KAHaEK&pid=Api&P=0',
    'Jute': 'https://tse3.mm.bing.net/th?id=OIP.NPV5SWXPEl0YQ7NQx1i2bAHaDj&pid=Api&P=0',
    'Peas & beans (Pulses)': 'https://www.gettystewart.com/wp-content/uploads/2020/02/pulses-w.jpg',
    'Blackgram': 'https://vaya.in/news/wp-content/uploads/2019/04/blackgram.jpg',
    'Paddy': 'https://tse1.mm.bing.net/th?id=OIP.TuoaJpTgtx3iMPLlDV-WQgHaD4&pid=Api&P=0',
    'Pineapple': 'https://tse4.mm.bing.net/th?id=OIP.OK8g3B00NmrRGsvxTsjBvgHaE8&pid=Api&P=0',
    'Barley': 'https://tse3.mm.bing.net/th?id=OIP.7jpgpih43XjvStml2V7UcAHaEn&pid=Api&P=0',
    'Guar seed': 'https://5.imimg.com/data5/ANDROID/Default/2021/5/CA/BV/WZ/46055372/product-jpeg-500x500.jpeg',
    'Other Cereals & Millets': 'https://tse2.mm.bing.net/th?id=OIP.s6ZTpvCWd18GQDO5p1omfgHaEK&pid=Api&P=0',
    'Turnip': 'https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/284/284815/a-bunch-of-turnips-on-a-table.jpg?w=1155&h=1734',
    'Carrot': 'https://tse2.mm.bing.net/th?id=OIP.NlbKxgrBn0dLKBQ_rDa-UAHaE8&pid=Api&P=0',
    'Arcanut (Processed)': 'http://arecanut.org/wp-content/uploads/2010/09/arecanut-banner-3.jpg',
    'Atcanut (Raw)': 'https://image.shutterstock.com/image-photo/closeup-ripe-arecanut-raw-betel-260nw-129577400.jpg',
    'Cashewnut Processed': 'https://www.shellingmachine.com/wp-content/uploads/2018/05/Vietnam-cashew-nut-processing-industry.jpg',
    'Cashewnut Raw': 'https://tse1.mm.bing.net/th?id=OIP.gk7P5U7hNwF4ouJL7jbr6QHaFj&pid=Api&P=0',
    'Cardamom': 'https://tse2.mm.bing.net/th?id=OIP.JHqBGcS5xkJpdFwCF2JTzQHaGj&pid=Api&P=0',
    'Rubber': 'https://tse1.mm.bing.net/th?id=OIP.JueZulygIz-7j4_Ibge0ggHaD7&pid=Api&P=0',
    'Bitter Gourd': 'https://tse4.mm.bing.net/th?id=OIP.e5gBrPaDC9CIlXYxF1827QHaFj&pid=Api&P=0',
    'Drum Stick': 'https://tse3.mm.bing.net/th?id=OIP.DhJ9SFlhIzq0pdJ3LYhvVAHaFj&pid=Api&P=0',
    'Jack Fruit': 'https://tse2.mm.bing.net/th?id=OIP.lIFrTCYq9cLhgr4ZfmS2tQHaFj&pid=Api&P=0',
    'Snak Guard': 'https://www.ayurvedalive.in/wp-content/uploads/2017/04/snakegourd.jpg',
    'Pump Kin': 'https://www.asiafarming.com/wp-content/uploads/2016/04/Pumpkin-Cultivation.jpg',
    'Tea': 'https://tse1.mm.bing.net/th?id=OIP.rOAh3GKeDyoD3p8zKf-CxAHaE7&pid=Api&P=0',
    'Coffee': 'https://www.thoughtco.com/thmb/rkMuni0DYnhjO94mqy5fzbRxDXU=/2233x1256/smart/filters:no_upscale()/GettyImages-936840910-5c8ea8b2c9e77c0001ff0ae6.jpg',
    'Cauliflower': 'https://tse4.mm.bing.net/th?id=OIP.WzCQQxOpa_bByVvY2Z2UugHaEK&pid=Api&P=0',
    'Other Citrus Fruit': 'https://tse1.mm.bing.net/th?id=OIP._bFbIoAQUtfXs2UcXBI2dQHaD4&pid=Api&P=0',
    'Water Melon': 'https://tse3.mm.bing.net/th?id=OIP.zuXzRP5NrBsBMKhorC7sJAHaHa&pid=Api&P=0',
    'Total foodgrain': 'https://www.thestatesman.com/wp-content/uploads/2017/08/1494359592-grain-getty-517.jpg',
    'Kapas': 'https://m.media-amazon.com/images/I/51RH1++6VTL._SX466_.jpg',
    'Colocosia': 'https://www.jlbg.org/data/galleries/Colocasia_(Elephant_Ear)/Colocasia-esculenta-Maui-Gold3.jpg',
    'Lentil': 'https://www.naturalfoodseries.com/wp-content/uploads/2017/08/Lentils_seeds-1600x832.jpg',
    'Bean': 'https://lh6.googleusercontent.com/-7s5wKS46DCs/TXk1VSoXHkI/AAAAAAAAAL4/RMT6fOH0FPo/s1600/DSC05574.JPG',
    'Perilla': 'http://www.onlineplantguide.com/Image%20Library/P/5936.jpg',
    'Rajmash Kholar': 'https://jammuvirasat.com/wp-content/uploads/2019/07/Rajmash-bhaderwah-kidney-beans.jpg',
    'Ricebean (nagadal)': 'https://tse1.mm.bing.net/th?id=OIP.ikaUCm4X9HBfdycyZ6fIhQHaE8&pid=Api&P=0',
    'Ash Gourd': 'https://ae01.alicdn.com/kf/HTB14j2ndEEIL1JjSZFFq6A5kVXa4/10-Pcs-New-Bottle-Gourd-Bonsai-Big-Wine-Gourd-Spoon-Lagenaria-Siceraria-Bonsai-Calabash-Gourd-Vegetable.jpg',
    'Beet Root': 'https://tse1.mm.bing.net/th?id=OIP.muQHr4z9SDFfXFZQIpwFYwHaHa&pid=Api&P=0',
    'Lab-Lab': 'https://zirp-zimbabwe.org/wp-content/uploads/2021/04/Website-news-1.png',
    'Ribed Guard': 'https://tse3.mm.bing.net/th?id=OIP.XNfE35NZRuQ9RJWPtdFmuAHaEh&pid=Api&P=0',
    'Yam': 'https://www.asiafarming.com/wp-content/uploads/2018/08/Growing-Yam..jpg',
    'Apple': 'https://storage.googleapis.com/webhosting-corpmagazine/wp-media/2014/12/P9230024.jpg',
    'Peach': 'http://mediad.publicbroadcasting.net/p/kstx/files/styles/x_large/public/201704/6040288634_3ba47c5195_o.jpg',
    'Pear': 'https://cdn.freshfruitportal.com/2016/07/PEars-Oneonta.jpg',
    'Plums': 'https://tse3.mm.bing.net/th?id=OIP.zVQN4j0VLp7n3EUlcFutmQHaFj&pid=Api&P=0',
    'Litchi': 'https://tse3.mm.bing.net/th?id=OIP.VKOF8KBV90cifTFnDckNpwHaFj&pid=Api&P=0',
    'Ber': 'https://www.agrifarming.in/wp-content/uploads/2019/07/eCKxiDMc.jpg',
    'Other Dry Fruit': 'https://tse4.explicit.bing.net/th?id=OIP.86DdMW-Gt-kAbi4QRk1rqQHaE8&pid=Api&P=0',
    'Jute & mesta': 'http://www.apnikheti.com/upload/crops/4325idea99mesta_crop_banner.jpg'
}
